name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: read-all

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build com Maven
        run: mvn -B clean install

      - name: Rodar Testes Unitários
        run: mvn test